### ISSUE TITLE
How to use secret Credentials for CI and deployed projects without including ut i VCS 

### ISSUE THREAD

**Issue by holgertidemand** [CraftAcademy/CraftOverflow#25]
## Problem
How does my code know about files in the VCS without them begin in the VCS?

### Background
Feching new from api
Can't have my api key in VCS, but my code  dosen't work without the file i stored it in.
Second time have have been told to remove secret credentials from VCS without an explanation on how to make it work.

#### Implementation code

```ruby
secret.yml 

development:
  secret_key_news_api: e9b2cff169de4096a9d34df4e3742ab2

test:
  secret_key_news_api: e9b2cff169de4096a9d34df4e3742ab2

production:
  secret_key_news_api: <%= ENV["SECRET_KEY_NEWS_API"] %>

.gitignore

config/secret.yml
```

relented PR https://github.com/CraftAcademy/dream_team_publications/pull/21

**Comment by tochman** [comment]
What do you mean you have not been told how to do it? You have used the DotEnv gem before to start with. You’ve also “been told” how to set up environmental variables on a CI service. And, finally, I pointed you to the Rails 5.2 release notes to read up on the new way of doing this using the new mechanism to store secrets and credentials introduced in that release. 

About the way you formulate the question: you fail to mention what CI service you are using. 

You also fail to mention what steps you’ve taken to resolve the issue yourself. 

Also, please provide the error messages you are getting.

**Comment by holgertidemand** [comment]
Okay Thomas. 
Loose the attitude.
I pay you money for this!
Just help us understand!

**Comment by tochman** [comment]
On Monday I will. And we’ll also have a long talk, you and I.

**Comment by holgertidemand** [comment]
We fixed this problem.
We had to add the master key as ENV on https://semaphoreci.com/

**Comment by tochman** [comment]
In what way is this resolved? I see that the PR related to this issue is still pending with no solution in sight.

**Comment by tochman** [comment]
I can see that now. I wasn't the case when I reopend the issue. I still don't see how the problem was resolved.

**Comment by holgertidemand** [comment]
Well we added the Master key to semaphore. Can't give you a better answer

**Comment by davidboll** [comment]
**So to make this work you need to do the following:**

1. Go to Semaphore / Project settings / Environment Variables
2. Add a new environment variabel 
3. Set RAILS_MASTER_KEY as the name 
4. Set the content to be the key that is stored in master.key.
5. Encrypt the content

That should do it for the setup on Semephore. 

Now in your project you need to run ``` EDITOR="atom --wait" rails credentials:edit ``` and the add your keys to the file. Save and push and good luck :)

**Comment by holgertidemand** [comment]
Thank you for the clear answer David! Really helpful.

**Comment by holgertidemand** [comment]
Sorry David that didn't do the trick! Think something else is broken now!

**Comment by tochman** [comment]
@davidboll Can we plese see what your settings in `config/application.rb` look like?

**Comment by davidboll** [comment]
```require_relative 'boot'

require "rails"
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"

Bundler.require(*Rails.groups)

module Paps
  class Application < Rails::Application
    config.load_defaults 5.2

    config.generators do |generate|
      generate.helper false
      generate.assets false
      generate.view_specs false
      generate.helper_specs false
      generate.routing_specs false
      generate.controller_specs false
      generate.system_tests false
    end

    config.stripe.secret_key = Rails.application.credentials.stripe[:stripe_secret]
    config.stripe.publishable_key = Rails.application.credentials.stripe[:stripe_app]
    config.stripe.endpoint = '/payment/stripe-integration'
  end
end
```

**Comment by holgertidemand** [comment]
We are getting this error on CI and locally 
``` 
  Given I am on the "Index" page                  # features/step_definitions/basic_steps.rb:7
      Nil location provided. Can't build URI. (ActionView::Template::Error)
      ./app/views/index/index.html.erb:15:in `block in _app_views_index_index_html_erb__3155911067542804302_70336813335860'
      ./app/views/index/index.html.erb:11:in `each'
      ./app/views/index/index.html.erb:11:in `_app_views_index_index_html_erb__3155911067542804302_70336813335860'
      ./features/step_definitions/basic_steps.rb:8:in `"I am on the {string} page"'
      features/user_can_visit_index_page.feature:7:in `Given I am on the "Index" page'
```

**Comment by tochman** [comment]
And what does your `config/application.rb`, your `credentials.yml.enc` (without values) and your `app/views/index/index.html.erb` look like?

**Comment by holgertidemand** [comment]
Index.html
```  
<h1>Dream Team Publications</h1>

<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Register', new_user_registration_path %></li>
<% end %>

<% @api_news_feed.each do |article|%>
  <article id="news">
    <h1><%=article.title %></h1>
    <p><%=article.description %></p>
    <%= image_tag(article.urlToImage, size: '150x100', alt: "Source not found") %>
  </article>
<% end %>
``` 
application
```
require_relative 'boot'

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "action_cable/engine"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)
Dotenv::Railtie.load


module Dreamteam
  class Application < Rails::Application
    config.load_defaults 5.2
    config.generators do |generate|
      generate.helper false
      generate.assets false
      generate.view_specs false
      generate.helper_specs false
      generate.routing_specs false
      generate.controller_specs false
      generate.system_tests false
    end
  end
end
``` 
credentials
```
# aws:
#  access_key_id: 123
#  secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: 571b45411a237471c150cf6b23be27a4a7ecae17f42e8664741b0bba2daa4cb228fb54906f87e434625176e551eb52fb337966630167a95d4e11ae64348db955
news:
  news_api_key: ############
```

index contoller 
``` 
require 'news-api'
class IndexController < ApplicationController
  def index
    api_key = News.new(Rails.application.credentials.news[:news_api_key])
    @api_news_feed = api_key.get_top_headlines(category: 'technology', country: 'us', pageSize: 5)
  end
end

```

**Comment by tochman** [comment]
I don't think you have to require the gem in your controller. Rails takes care of that for you. I would then set a `binding.pry` in the ìndex`action and run this code manually. See if the News API is responding.

**Comment by holgertidemand** [comment]
We are successfully creating the object but now the request to the server fails.
``` 
From: /Users/holgertidemand/projects/bootcamp/week8/dream_team_publications/app/controllers/index_controller.rb @ line 6 IndexController#index:

    3: def index
    4:   binding.pry
    5:   api_key = News.new(Rails.application.credentials.news[:news_api_key])
 => 6:   @api_news_feed = api_key.get_top_headlines(category: 'technology', country: 'us', pageSize: 5)
    7: end

[1] pry(#<IndexController>)> api_key
=> #<News:0x007f8e48cefaf8 @api_key="e9b2cff169de4096a9d34df4e3742ab2">
[2] pry(#<IndexController>)> next

From: /Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/rescue.rb @ line 24 ActionController::Rescue#process_action:

    21: def process_action(*args)
    22:   super
    23: rescue Exception => exception
 => 24:   request.env["action_dispatch.show_detailed_exceptions"] ||= show_detailed_exceptions?
    25:   rescue_with_handler(exception) || raise
    26: end


```

**Comment by holgertidemand** [comment]
Sorry the request is working.

**Comment by holgertidemand** [comment]
But we are still getting the error

**Comment by holgertidemand** [comment]
Removed ``` <%= image_tag(article.urlToImage, size: '150x100', alt: "Source not found") %> ``` from index.html
Passed locally & CI

**Comment by tochman** [comment]
What you are describing is not related to the original issue/question. This issue is resolved.
